### ISSUE TITLE
System.Text.Json "high severity" security issue.

### ISSUE THREAD

**Issue by archanox** [FoundatioFx/Foundatio#330]
There's a reported "high severity" security issue with System.Text.Json 8.0.4

https://github.com/advisories/GHSA-8g4q-xg66-9fp4

**Comment by ejsmith** [comment]
Thanks. If you are referencing a higher version of the nuget package in your app, it will use that version instead of the transitive dependency version from Foundatio. Generally, we don't like to force people to be running latest, but I guess in the case of a security vulnerability we should update it.

**Comment by niemyjski** [comment]
It's already been updated but release hasn't been tagged

**Comment by niemyjski** [comment]
We'll try pushing a new release soon

**Comment by niemyjski** [comment]
v11.0.6 is going out
